jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew assembleDebug
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
